### ISSUE TITLE
need to restart on new content

### ISSUE THREAD

**Issue by hannesm** [Engil/Canopy#41]
maybe #37 broke this slightly?  need further investigation

**Comment by abbysmal** [comment]
I am looking into it right now…
Looks like the cache is somehow misbehaving.
The article is added inside the repo (your can access it after pulling via its URL), but not shown in the article list. (in the top bar or the listing page).
If you force refresh (telling the browser to ignore the cache), you can see the correct version of the page with the added article.
Will look into it further today, maybe @voila has some ideas ?

**Comment by hannesm** [comment]
oh, so it is etag related maybe?

**Comment by hannesm** [comment]
i wonder whether the new git release solves this as a side effect then ;)

**Comment by hannesm** [comment]
(and might have the same root cause as #33)

**Comment by abbysmal** [comment]
Well I don't think it's related to ocaml-git but more like me implementing things very badly. (the functions to dig inside the history).
But yeah I also have a feeling it is related to this issue, will try to debug this

**Comment by voila** [comment]
I think this predates my last PR, as I noticed this on the master branch before my PR was merged...

**Comment by abbysmal** [comment]
Yup, might be related to the last updated date not being correct after pulling, that would explain the caching issue (since we rely on those dates for that)

**Comment by voila** [comment]
Just to clarify, we are talking of having to empty the browser cache to see new content, after hitting `/push` ?

**Comment by hannesm** [comment]
@voila yes. I think @Engil is right that the last updated is not correct after `/push` was hit.

**Comment by abbysmal** [comment]
I looked a little bit in the codebase, and this is due to the fact that we rely on the updated field to know if we send a not_modified.

Main problem is that, if we add a file in the repo, this won't change the updated field of each individual article, resulting in the same page being served from the cache (and the newly added content doesn't show up since the cached pages (either the indexes, taglists or even the navbar) don't know about it.).

I'm not too sure on how to handle that.
Only solution I have in mind right now is caching pages based on the repository updated date, and not each article updated field. (so, that means: if the repo is updated, the cache for all pages will be dropped)

This isn't great but I can't find anything better given how things are currently architectured

**Comment by hannesm** [comment]
thx @Engil, but my intuition was:
- each article produces an Etag based on its last updated date
- each listing produces an Etag based on the last updated article of that listing (and I thought code for this would be: for [tags](https://github.com/Engil/Canopy/blob/cbe63916df7f0107d64f5e8e321405dd76f964e4/canopy_dispatch.ml#L83), for [articles](https://github.com/Engil/Canopy/blob/cbe63916df7f0107d64f5e8e321405dd76f964e4/canopy_dispatch.ml#L103) in a directory, for [all tags](https://github.com/Engil/Canopy/blob/cbe63916df7f0107d64f5e8e321405dd76f964e4/canopy_dispatch.ml#L72) (actually the last store update)

when I merged this morning some typo fixes, the website etag did also not update (thus I was served the old content) -- I again (see #33) had to restart to see the updates (likely a force reload would've been enough, but this would need to be done on each client, and I don't have control over all clients)

EDIT: from what I saw I still have the suspicion that in my setup the `updated` timestamp of the articles is not always correct...

**Comment by hannesm** [comment]
fixed with #43...
