### ISSUE TITLE
feed issues

### ISSUE THREAD

**Issue by hannesm** [Engil/Canopy#44]
[via](https://github.com/Engil/Canopy/pull/12#issuecomment-206937729) (so that we do not forget), esp buenzli's comment [here](https://github.com/Engil/Canopy/pull/12#issuecomment-212639845) to use [this scheme](https://github.com/mirage/mirage-www/issues/319#issue-75976342).

current issues from w3 feed validator:

```
    line 1, column 100: id must be a full and valid URL: full%20stack%20engineer [help]
        ...  rel="self"/><id>full%20stack%20engineer</id><title type="text">full sta ...
                                                     ^
    line 47, column 10: scheme must be a full and valid URL: /tags/security (13 occurrences) [help]
        </content><category scheme="/tags/security" term="security"/><category schem ...
                  ^
    line 47, column 159: id is not a valid TAG: tag:,2016-5-3:Posts/BadRecordMac/1462282097 (5 occurrences) [help]
        ... :,2016-5-3:Posts/BadRecordMac/1462282097</id><title type="text">Catch th ...
                                                     ^

In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
    line 1, column 73: Relative href value on self link: /atom [help]
        <feed xmlns="http://www.w3.org/2005/Atom"><link href="/atom" rel="self"/><id ...
                                                                                 ^
    line 491, column 314: Two entries with the same value for atom:updated: 2016-04-24T22:01:50-00:00 [help]
        ... title><updated>2016-04-24T22:01:50-00:00</updated><author><name>hannes</ ...
```

**Comment by voila** [comment]
In order to validate the feed, of few URLs should be absolute:

`<category scheme="https://hannes.nqsb.io/tags/background" term="background"/>
`

and it is "advised" this one be absolute too:

`<link href="https://hannes.nqsb.io/atom" rel="self"/>
`

So the question is, where do I find the domain ? Should it be passed as a command line parameter (as is the blog name, etc...) ?

**Comment by voila** [comment]
I have a just pushed a [commit](https://github.com/voila/Canopy/commit/f799b7bdce3e29f3139892d2fd169187f28d61e3), to my fork, which fixes these validation errors

I used an urn:uuid: scheme for the feed id (it needs to be provided on the command line via the --uuid flag)

According to [these comments](https://github.com/mirage/mirage-www/issues/319#issue-75976342), entries id should also never change, but I don't know how to use urn:uuid: or rather, where to store them... Should they be added to Canopy_article.t and generated for each new article ?

Another flag I added is --root, to provided the blog URL, some feed errors were due to URLs being relative...

**Comment by hannesm** [comment]
@voila that sounds great (sorry currently low on time to look into your patch, will hopefully find some time over the weekend).  What I'd do for entry ids is to reuse the uuid provided on the command line together with the initial creation date of the entry (as mentioned by daniel [here](https://github.com/mirage/mirage-www/issues/319#issue-75976342)).

**Comment by voila** [comment]
I have changed the entries id accordingly: https://github.com/voila/Canopy/commit/b96db425941d851a0306504b63c8d8cc0ea514c2

**Comment by hannesm** [comment]
merged and works! :D thanks!
