### ISSUE TITLE
add config to data repository

### ISSUE THREAD

**Issue by hannesm** [Engil/Canopy#45]
there are too many command-line arguments already, thus (also [via this issue](https://github.com/Engil/Canopy/pull/12)) we should have some setup in the data repository with those elements we don't need for startup:
- title
- index page
- domain name
- uuid for feed (or seed for uuid)

**Comment by voila** [comment]
Would it make any sense to put the config file and the articles in two separate branches ?

It seems clumsy to check whether we are folding over the config, instead of a regular article, when we [fill the cache](https://github.com/Engil/Canopy/blob/master/canopy_store.ml#L79)

**Comment by abbysmal** [comment]
I think putting it in another branch adds too much complexity for everyone (for the user and us). (how do we handle a config file update ? Do we need to inspect two branches all the time (when new content is pulled) ? It is possible, but adds too much complexity to the codebase in my opinion)

Checking if we are reading the config file while filling the cache doesn't look too bad to me, since we got the key name somehow we can detect it pretty easily, and it's not a huge performance problem either since it happens once every new pull.

In which format should the config file be ? We keep the same as in the headers ?

**Comment by hannesm** [comment]
I'd put the config file in the master branch. Using the same file format as in the article headers sounds good to me.  Hardcoding the name should be fine (maybe `canopy.conf`?).

**Comment by hannesm** [comment]
thought a bit more about other resources, such as favicon.ico or images in general... it might make sense to have Canopy ignore files which start with `.` for displaying, but nevertheless serves them -- it already handles `static` magically, but `static` is filled at compile time with font, JS, etc. -- maybe that should in the same go move into the data repository (and having `static/config.txt` sounds good to me as well)?  right now I've to depend on external servers to embed images into my canopy instance, which I dislike (should be self-hosted)...

**Comment by voila** [comment]
Do you think moving the static assets to the data repository should be a new issue, separate from the config file ?

**Comment by hannesm** [comment]
I took the opportunity of a free evening and put the static assets into the git remote (see #64).  The piece missing is (after merging that PR) to move the configuration bits to the git remote.  'coz I'm lazy I'll use s-expressions in a .config file.

**Comment by voila** [comment]
So the config is split between a "startup config" (which does not change) and a "repo config" (which can be updated via the push_hook)?

Instead of using s-expressions, couldn't we have a config folder and a file each for uuid, root, blog_name and index_page? That way, we could lookup them up by their key (eg. ["config"; "uuid"]) in the store cache  .

**Comment by hannesm** [comment]
@voila excellent idea with the config folder as key value store! you want to do this? I guess all needed for startup is certificates (for tls), git remote, network configuration, and push_hook_path).  The rest can be in the git remote

**Comment by hannesm** [comment]
if you base on #64, we can use `.config` (everything with `.` is excluded from the data processing)

**Comment by voila** [comment]
sure, I'll give it a go :)

**Comment by hannesm** [comment]
#71 does this
