### ISSUE TITLE
fetch from a specific git branch

### ISSUE THREAD

**Issue by gasche** [Engil/Canopy#68]
My understanding is that the blog content is a git directory that can be manipulated using the usual `git` tools. In particular, a natural workflow for me is to fork an existing blog (a git repository), and prepare a pull request to propose a change by creating a fresh branch and doing a few commits in that. Before sending the PR, I want to check the result to tell if it renders as I expect.

However, it does not seem to be possible at the moment to specify a branch to use on the remote to fetch content. I tried `-r URL#branch`, or `-r URL:branch`, and neither work.

```
$ ./mir-canopy -r https://github.com/gasche/icfp2016-blog#student-volunteer-blog-posts -i Welcome -p 8080 -u 12345
Manager: connect
Manager: configuring
2016-10-15 01:58.13: INF [git.memory] Reading HEAD
Pulling repository
2016-10-15 01:58.14: ERR [git.http] with_http: 404 Not Found
Raised at file "pervasives.ml", line 32, characters 22-33
Called from file "src/core/lwt.ml", line 653, characters 66-69
2016-10-15 01:58.14: ERR [git.mirage] Git_mirage.IO.read_exactly: expecting 4, got 0
Fail pull (Failure "Git_mirage.IO.read_exactly: expecting 4, got 0")
2016-10-15 01:58.14: INF [git.memory] Reading HEAD
2016-10-15 01:58.14: INF [git.memory] Reading refs/heads/master
2016-10-15 01:58.14: INF [git.memory] Reading HEAD
2016-10-15 01:58.14: INF [git.memory] Reading HEAD
2016-10-15 01:58.14: INF [git.memory] Reading refs/heads/master
HTTP server listening on port 8080
```

**Comment by gasche** [comment]
I have a preliminary patch in 34ee98dd93a747f4f58132816abf3340ae8583c9, it roughly works but needs nicer code.

**Comment by hannesm** [comment]
IMHO your patch is highly appreciated (but maybe @Engil has a different opinion), and I agree that the workflow to test a custom branch of the data repository should be possible (as well as local git repositories, as mentioned in #67).

**Comment by abbysmal** [comment]
Currently traveling so I am truly sorry for the lack of answers from my side. 😇
I think this is a nice solution, nothing was done with the branches so far as I wasn't sure about what could be done with them within Canopy.
This seems simple enough, and I have nothing to add about the patch, so thank you!
(go ahead and merge later if you want @hannesm, if I'm not around)

Only nitpick but I am definitely to blame about this, we should definitely switch to a configuration that is in-repo instead of being full-command line, where we keep adding command line arguments… (perhaps to add here #60 ? And a dedicated issue ?)

Sorry again about my slow answers, I will try to take a look at the other issues and answer in the next days!
