### ISSUE TITLE
feature request: Support of author URL

### ISSUE THREAD

**Issue by olleolleolle** [Engil/Canopy#88]
The `author:` frontmatter metadata can contain rich text in the form of Markdown.

It would be cool if that were rendered.

The author information on some of the articles here _could_ look cooler with Markdown:
http://canopy.mirage.io/tags/help%20needed

**Update**: Changed the feature request to be about adding a `author_url` optional metadata field, which (if present) would render a hyperlink around the `author` name.

**Comment by abbysmal** [comment]
Hi,
I don't have any strong opposition to that feature, except that it would probably allow to break the rendered site structure (by inserting, let's say, a markdown paragraph in the author field, which isn't likely that big of a problem since one could also copy-paste an indecent amount of characters in the said field.)
Other solution would be adding an author_url field, to keep it under control, but if more use cases can be found markdown could be allowed here.

**Comment by olleolleolle** [comment]
There’s wisdom here. I agree with the idea of restricting metadata. It gives the site designer more freedom.

**Comment by olleolleolle** [comment]
Thanks, @wallymathieu and @Engil!
